version: '3'
services:
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto
  nodered:
    image: "nodered/node-red-docker:rpi"
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
